name: build and publish imgs workflow

on:
  workflow_call:
    inputs:
      push:
        required: true
        type: boolean

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CUDA_VER:
          - "11.5.1"
          - "11.4.1"
          - "11.2.2"
          - "11.0.3"
        PY_VER:
          - "3.8"
          - "3.9"
        LINUX_VER:
          - "ubuntu18.04"
          - "ubuntu20.04"
          - "centos7"
          - "centos8"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - if: ${{ secrets.GPUCIBOT_DOCKERHUB_USER != '' && secrets.GPUCIBOT_DOCKERHUB_TOKEN != '' }}
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.GPUCIBOT_DOCKERHUB_USER }}
          password: ${{ secrets.GPUCIBOT_DOCKERHUB_TOKEN }}
      - name: Build and push
        timeout-minutes: 10
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ matrix.CUDA_VER >= '11.2.2' && matrix.LINUX_VER != 'centos7' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          push: ${{ inputs.push }}
          pull: true
          build-args: |
            CUDA_VER=${{ matrix.CUDA_VER }}
            LINUX_VER=${{ matrix.LINUX_VER }}
            PY_VER=${{ matrix.PY_VER }}
          tags: rapidsai/mambaforge-cuda:${{ matrix.CUDA_VER }}-base-${{ matrix.LINUX_VER }}-py${{ matrix.PY_VER }}
